version: '2'
services:
  web:
    build: .
    container_name: hackucsc2017
    ports:
     - "3000:3000"
    environment:
     - DB_HOST=${DB_HOST}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
